# Generated by Django 5.2.2 on 2025-06-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0002_branch_organization_remove_review_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photos',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='provider',
            field=models.CharField(blank=True, choices=[('yandex', 'Яндекс'), ('google', 'Гугл'), ('2gis', '2GIS'), ('vlru', 'VL.RU')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
