# Generated by Django 5.2.2 on 2025-06-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0003_review_photos_review_provider_review_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='twogis_map_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='yandex_map_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
