# Generated by Django 5.2.2 on 2025-06-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0005_rename_twogis_map_link_branch_twogis_map_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
