# Generated by Django 5.2.2 on 2025-06-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0006_alter_review_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='twogis_review_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='twogis_review_cout',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
