# Generated by Django 5.2.2 on 2025-06-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0007_branch_twogis_review_avg_branch_twogis_review_cout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='twogis_review_cout',
            new_name='twogis_review_count',
        ),
        migrations.AddField(
            model_name='branch',
            name='vlru_review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='vlru_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
