# Generated by Django 5.2.2 on 2025-06-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0008_rename_twogis_review_cout_branch_twogis_review_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='vlru_review_avg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
