# Generated by Django 5.2.2 on 2025-06-12 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0010_alter_branch_vlru_review_avg'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchIPMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_mappings', to='common_parser.branch')),
            ],
        ),
    ]
