# Generated by Django 5.2.2 on 2025-06-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0011_branchipmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='yandex_review_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='yandex_review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
