# Generated by Django 5.2.2 on 2025-06-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0012_branch_yandex_review_avg_branch_yandex_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(default=43, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
