# Generated by Django 5.2.2 on 2025-06-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0013_alter_organization_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='vlru_org_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
