# Generated by Django 5.2.2 on 2025-06-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0014_branch_vlru_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='twogis_parse_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='vlru_parse_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='yandex_parse_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
