# Generated by Django 5.2.2 on 2025-06-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0015_branch_twogis_parse_date_branch_vlru_parse_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewurl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
