# Generated by Django 5.2.2 on 2025-06-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0016_review_reviewurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewurl',
        ),
        migrations.AddField(
            model_name='review',
            name='review_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
