# Generated by Django 5.2.2 on 2025-06-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0017_remove_review_reviewurl_review_review_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='yandex_map_url',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
    ]
