# Generated by Django 5.2.2 on 2025-06-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0018_alter_branch_yandex_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='google_map_url',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='google_parse_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='google_review_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='google_review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
