# Generated by Django 5.2.2 on 2025-06-23 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0019_branch_google_map_url_branch_google_parse_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('url', models.URLField(unique=True)),
                ('parse_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('preview', models.URLField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('organization', 'address'), name='unique_organization_address'),
        ),
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='common_parser.playlist'),
        ),
    ]
