# Generated by Django 5.2.2 on 2025-06-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0020_playlist_video_branch_unique_organization_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='provider',
            field=models.CharField(blank=True, choices=[('youtube', 'Ютуб'), ('vk', 'Вк')], max_length=50, null=True),
        ),
    ]
