# Generated by Django 5.2.2 on 2025-06-23 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0021_playlist_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistIPMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_mappings_playlist', to='common_parser.playlist')),
            ],
        ),
    ]
