# Generated by Django 5.2.2 on 2025-06-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0022_playlistipmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
