# Generated by Django 5.2.2 on 2026-08-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0025_alter_video_preview'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('branch', 'author', 'content', 'provider'), name='unique_review_per_branch_author_content_provider'),
        ),
    ]
