# Generated by Django 5.2.2 on 2026-08-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0026_review_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='vlru_org_id',
        ),
    ]
