# Generated by Django 5.2.2 on 2026-08-10 19:14

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0028_alter_review_rating_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchipmapping',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='playlistipmapping',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='provider',
            field=models.CharField(blank=True, choices=[('yandex', 'Яндекс'), ('google', 'Гугл'), ('2gis', '2GIS'), ('vlru', 'VL.RU')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
