# Generated by Django 5.2.2 on 2026-08-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0030_apiclient_and_drop_ip_mappings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
